# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['say_hello']

# Cell
def say_hello(to):
    "SAy hellO tO sOmEoNe"
    return f'Hello {to}. How was your day?'